name: CI Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        scala-version: [ "3" ]
        target-platform: [ "JVM" ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: 'sbt'
        java-version: 11
    - name: Install sam cli
      run: |
        wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
        sudo ./sam-installation/install --update
        sam --version
    - name: Install libidn2-dev libcurl3-dev
      if: matrix.target-platform == 'Native'
      run: |
        sudo apt-get update
        sudo apt-get install libidn2-dev libcurl3-dev
        echo "STTP_NATIVE=1" >> $GITHUB_ENV
    - name: Compile
      run: sbt -v "compileScoped ${{ matrix.scala-version }} ${{ matrix.target-platform }}"
    - name: Compile documentation
      if: matrix.target-platform == 'JVM'
      run: sbt -v compileDocumentation